In [2]:
import numpy as np

In [43]:
a = np.array([1,2]) 
b= np.array([[4,2],[3,2]])
print(np.log(a))
print(np.exp(a))
print(np.linalg.inv(b))
c=np.linalg.inv(b)
print(np.dot(b,c)) 
print(np.linalg.det(b))
print(np.diag(b))

[0.         0.69314718]
[2.71828183 7.3890561 ]
[[ 1.  -1. ]
 [-1.5  2. ]]
[[1. 0.]
 [0. 1.]]
2.0
[4 2]


In [59]:
x = np.diag([1,2,3,4])
print(x)
print(np.trace(x))
print(np.zeros((2,2)))
print(np.ones((3,3)))
print(np.random.random((2,2)))
print(np.random.randn(2,2))
h=np.random.randn(2,2)
print(h.mean())
print(h.var())


[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
10
[[0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[7.07320496e-01 2.13249311e-01]
 [4.16678696e-04 5.58877345e-01]]
[[-1.10475423  0.72483776]
 [ 0.4991811  -1.12695573]]
-0.8541862862811586
1.2542812721934624


In [29]:
a = np.array([[5,2], [3, 4], [5, 6]])
print(a[a > 2]) 

[5 3 4 5 6]


In [5]:
print(a.dtype) 

int64


In [9]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(np.add(x, y))
print(np.subtract(x, y))
print(np.multiply(x, y)) #elementwise multiplication
print(np.divide(x, y))   #elementwise divison
print(np.sqrt(x))
print(x.dot(y))          #matrix multiplication
print(np.dot(x, y))      #matrix multiplication


[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]
[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]
10.0
[4. 6.]
[3. 7.]
[[1. 3.]
 [2. 4.]]


In [13]:
x = np.array([[1,2],[3,4]])
print(np.sum(x)) 
print(np.sum(x, axis=0))  # sum of each column
print(np.sum(x, axis=1))  # sum of each row
print(x.T)                #Transpose of a matrix             
y = np.empty_like(x)   # Create an empty matrix with the same shape as x


10
[4 6]
[3 7]
[[1 3]
 [2 4]]
[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [17]:
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))   # Stack 4 copies of v on top of each other
print(vv)


[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [18]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v
print(y)


[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [19]:
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
print(np.reshape(v, (3, 1)) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]
